# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: estimator.proto for package 'estimator'

require 'grpc'
require 'estimator_pb'

module Estimator
  module Estimate
    class Service

      include GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'estimator.Estimate'

      rpc :timeAndDistanceBetweenPoints, PointsInfo, DirectionsInfo
    end

    Stub = Service.rpc_stub_class
  end
end
